### ISSUE TITLE
Change concurrency

### ISSUE THREAD

**Issue by DomVinyard** [timdp/es6-promise-pool#27]
Can I call .start() and then subsequently change concurrency, it that supported behaviour?

**Comment by timdp** [comment]
That should work, yep. You can call `pool.concurrency(Number)` synchronously and it should take effect after the next promise fulfilment/rejection.

**Comment by DomVinyard** [comment]
Awesome, thanks. I was hoping to use it to toggle concurrency between say 10 and 0 for a downloader I'm writing (downloading millions of files!), in order to act as a kind of 'on/off' switch.

**Comment by DomVinyard** [comment]
Alright, I've just realised setting the concurrency to 0 throws an invalid concurrency error. Do you have any advice on how best to turn this module into something that can be toggled?

**Comment by timdp** [comment]
Hmm, that's a separate issue.

I'd have to look at the code in detail and see how much of it would work with a concurrency of 0. I have a feeling you'd need to sort of kick-start it after toggling it back from 0 to something "active", because it could potentially be stuck otherwise.

Way after writing this module, I discovered `bottleneck`, which might be a better fit here.

**Comment by DomVinyard** [comment]
Thanks, i've switched over to bottleneck - i really appreciate your help though, thank you

**Comment by timdp** [comment]
No problem!
