### ISSUE TITLE
Typescript definition file is not in the package

### ISSUE THREAD

**Issue by aight8** [timdp/es6-promise-pool#31]
The typescript definition file is in the repository but missing in the npm package.

btw: If the methods would have also a small but nice description it would be even better :)) Some of them are not so clean on the first sight.

**Comment by timdp** [comment]
Ahh, right, I snuck the typings into the package with [this commit](https://github.com/timdp/es6-promise-pool/commit/b9eaf0d261561fb8d8edfd63bfa7331e75e74304#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R66) but then neglected to publish a new version because I thought I'd only changed the build logic. My mistake.

I've just published version 2.4.5, which contains the typings. Thanks for the heads up!
